
jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "noteworthynicole-github"
    token:
      secure: "f3ae02fda201cd40d8ae2140bec988985f273b22"
script:
- ant build
- sonar-scanner

