language: java
jdk:
- oraclejdk8
  - oraclejdk8
  - openjdk11     # LTS
  - oraclejdk11

addons:
  sonarcloud:
    organization: "noteworthynicole-github"
    token:
      secure: "f3ae02fda201cd40d8ae2140bec988985f273b22"
script:
- ant build
- sonar-scanner

