language: java

sudo: false

install: true


addons:
 
sonarcloud:
   
	organization: "sonarcloud"
   
token:
     
	secure: 
"f3ae02fda201cd40d8ae2140bec988985f273b22"


jdk:
 - oraclejdk8


script:
 # JaCoCo is used to have code coverage, the agent has to be activated
 
- mvn sonar:sonar