language: java
jdk:
- oraclejdk8

node_js: "0.10"
install: "npm install"
script: "npm test"

matrix:
  include:
    - language: python
      python: 
        - 3.4
      before_install:
        - cd backend/
      install: 
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - 4.8
      before_install:
        - cd daemon/frontend
      install:
        - yarn install
      script:
        - yarn test


addons:
  sonarcloud:
    organization: "noteworthynicole-github"
    token:
      secure: "f3ae02fda201cd40d8ae2140bec988985f273b22"
script:
- ant build
- sonar-scanner

